### ISSUE TITLE
Is there any screenshot  for this software?

### ISSUE THREAD

**Issue by IamHuskar** [bomach-group-company/benji_crm#75]
can't login without an account .
some screenshots  for this software would be better for me .

**Comment by egideons** [comment]
@IamHuskar 
There are screenshots and you are not able to login because the apps' content is only available for in house members.

**Comment by IamHuskar** [comment]
> @IamHuskar 
> 
> There are screenshots and you are not able to login because the apps' content is only available for in house members.

got it

**Comment by IamHuskar** [comment]
> @IamHuskar There are screenshots and you are not able to login because the apps' content is only available for in house members.

hello. I was wonderning where can I download this app to test ?can I download form apple store or google play ?
